DROP TABLE impuesto_producto;
DROP TABLE descuento_lote;
DROP TABLE categoria_producto;
DROP TABLE pantalla_tipo_usuario;
DROP TABLE pantalla;
DROP TABLE tipo_usuario_empleado;
DROP TABLE tipo_usuario;
DROP TABLE detalle_movimiento;
DROP TABLE telefono_persona ;
DROP TABLE movimiento_producto;
DROP TABLE medicamentos;
DROP TABLE laboratorio;
DROP TABLE detalle_factura;
DROP TABLE lote;
DROP TABLE producto;
DROP TABLE presentacion;
DROP TABLE impuesto ;
DROP TABLE factura;
DROP TABLE descuento;
DROP TABLE cliente ;
DROP TABLE forma_pago ;
DROP TABLE categoria ;
DROP TABLE farmacia ;
DROP TABLE empleado ;
DROP TABLE persona;
DROP TABLE telefono;
DROP TABLE ciudad;
DROP TABLE municipio;
DROP TABLE departamento;